COMPANY_NAME_MAP = {
    # -----------------------------
    # NIFTY 50 (India)
    # -----------------------------
    "ADANIENT.NS": "Adani Enterprises",
    "ADANIPORTS.NS": "Adani Ports and SEZ",
    "APOLLOHOSP.NS": "Apollo Hospitals",
    "ASIANPAINT.NS": "Asian Paints",
    "AXISBANK.NS": "Axis Bank",
    "BAJAJ-AUTO.NS": "Bajaj Auto",
    "BAJFINANCE.NS": "Bajaj Finance",
    "BAJAJFINSV.NS": "Bajaj Finserv",
    "BEL.NS": "Bharat Electronics",
    "BHARTIARTL.NS": "Bharti Airtel",
    "BPCL.NS": "Bharat Petroleum",
    "BRITANNIA.NS": "Britannia Industries",
    "CIPLA.NS": "Cipla",
    "COALINDIA.NS": "Coal India",
    "DIVISLAB.NS": "Divi's Laboratories",
    "DRREDDY.NS": "Dr. Reddy's Laboratories",
    "EICHERMOT.NS": "Eicher Motors",
    "GRASIM.NS": "Grasim Industries",
    "HCLTECH.NS": "HCL Technologies",
    "HDFC.NS": "Housing Development Finance Corporation",
    "HDFCBANK.NS": "HDFC Bank",
    "HDFCLIFE.NS": "HDFC Life Insurance",
    "HEROMOTOCO.NS": "Hero MotoCorp",
    "HINDALCO.NS": "Hindalco Industries",
    "HINDUNILVR.NS": "Hindustan Unilever",
    "ICICIBANK.NS": "ICICI Bank",
    "INDUSINDBK.NS": "IndusInd Bank",
    "INFY.NS": "Infosys",
    "IOC.NS": "Indian Oil Corporation",
    "ITC.NS": "ITC Limited",
    "JSWSTEEL.NS": "JSW Steel",
    "KOTAKBANK.NS": "Kotak Mahindra Bank",
    "LT.NS": "Larsen & Toubro",
    "M&M.NS": "Mahindra & Mahindra",
    "MARUTI.NS": "Maruti Suzuki",
    "NESTLEIND.NS": "Nestle India",
    "NTPC.NS": "NTPC Limited",
    "ONGC.NS": "Oil and Natural Gas Corporation",
    "POWERGRID.NS": "Power Grid Corporation",
    "RELIANCE.NS": "Reliance Industries",
    "SBILIFE.NS": "SBI Life Insurance",
    "SBIN.NS": "State Bank of India",
    "SHREECEM.NS": "Shree Cement",
    "SUNPHARMA.NS": "Sun Pharmaceutical",
    "TATACONSUM.NS": "Tata Consumer Products",
    "TATAMOTORS.NS": "Tata Motors",
    "TATASTEEL.NS": "Tata Steel",
    "TCS.NS": "Tata Consultancy Services",
    "TECHM.NS": "Tech Mahindra",
    "TITAN.NS": "Titan Company",
    "ULTRACEMCO.NS": "UltraTech Cement",
    "UPL.NS": "UPL Limited",
    "WIPRO.NS": "Wipro",

    # -----------------------------
    # US Stocks (Big Tech + Popular)
    # -----------------------------
    "AAPL": "Apple Inc.",
    "MSFT": "Microsoft Corporation",
    "GOOGL": "Alphabet Inc. (Google)",
    "GOOG": "Alphabet Inc. (Google Class C)",
    "AMZN": "Amazon.com Inc.",
    "TSLA": "Tesla Inc.",
    "META": "Meta Platforms Inc. (Facebook)",
    "NVDA": "NVIDIA Corporation",
    "NFLX": "Netflix Inc.",
    "INTC": "Intel Corporation",
    "AMD": "Advanced Micro Devices",
    "IBM": "International Business Machines",
    "ORCL": "Oracle Corporation",
    "PYPL": "PayPal Holdings Inc.",
    "ADBE": "Adobe Inc.",
    "CRM": "Salesforce Inc.",
    "UBER": "Uber Technologies",
    "LYFT": "Lyft Inc.",
    "SHOP": "Shopify Inc.",
    "SQ": "Block Inc. (Square)",
    "SPOT": "Spotify Technology",
    "BABA": "Alibaba Group",
    "PDD": "Pinduoduo",
    "JD": "JD.com",
    "DIS": "Walt Disney Company",
    "NKE": "Nike Inc.",
    "MCD": "McDonald's Corporation",
    "SBUX": "Starbucks Corporation",
    "WMT": "Walmart Inc.",
    "COST": "Costco Wholesale",
    "PG": "Procter & Gamble",
    "PEP": "PepsiCo Inc.",
    "KO": "Coca-Cola Company",
    "JNJ": "Johnson & Johnson",
    "PFE": "Pfizer Inc.",
    "MRNA": "Moderna Inc.",
    "XOM": "Exxon Mobil",
    "CVX": "Chevron Corporation",
    "JPM": "JPMorgan Chase & Co.",
    "GS": "Goldman Sachs",
    "BAC": "Bank of America",
    "C": "Citigroup Inc.",
    "V": "Visa Inc.",
    "MA": "Mastercard Inc.",

    # -----------------------------
    # Popular Cryptos
    # -----------------------------
    "BTC": "Bitcoin",
    "ETH": "Ethereum",
    "SOL": "Solana",
    "ADA": "Cardano",
    "XRP": "XRP (Ripple)",
    "DOGE": "Dogecoin",
    "DOT": "Polkadot",
    "MATIC": "Polygon",
}